#pragma once
static constexpr char transfer_page[]=R"HTML(<!doctype html>
<html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pocket Home · 文件传输</title>
<style>
:root{color-scheme:dark;font:15px system-ui,-apple-system,sans-serif;color:#edf3fc;background:#0b101b}*{box-sizing:border-box}body{margin:0}main{max-width:900px;margin:60px auto;padding:0 24px}header{display:flex;align-items:center;justify-content:space-between;gap:20px}small,.muted{color:#9eaec5}h1{font-size:30px;margin:12px 0}h2{font-size:19px;margin:0 0 16px}.badge{border:1px solid #34584e;border-radius:30px;padding:8px 14px;color:#71e6b1;white-space:nowrap}section{background:#151e2d;border:1px solid #29374d;border-radius:20px;padding:24px;margin-top:24px}button,.pick{border:0;border-radius:10px;padding:10px 16px;background:#293951;color:#edf3fc;font:inherit;cursor:pointer}button:hover,.pick:hover{background:#38506e}button:disabled{opacity:.4;cursor:wait}.primary{background:#71e6b1;color:#082318}.primary:hover{background:#9beec7}input{background:#0b1321;color:white;border:1px solid #44536a;border-radius:10px;font:inherit;padding:12px;max-width:100%}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}#drop{border:1px dashed #4b6683;border-radius:15px;text-align:center;padding:30px 16px;margin:20px 0;background:#0f1928}#drop.over{border-color:#71e6b1;background:#172f2b}#drop p{color:#a8b7cb;margin:12px 0}progress{width:100%;height:8px;accent-color:#71e6b1;margin:14px 0}#message{min-height:24px;overflow-wrap:anywhere}#crumb{overflow-wrap:anywhere;flex:1}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{text-align:left;padding:14px 8px;border-bottom:1px solid #29374d}th{font-size:13px;color:#91a5be}td:first-child{overflow-wrap:anywhere}th:nth-child(2){width:95px}th:last-child{width:165px}td button{padding:7px 10px;margin:2px;font-size:13px}.danger{color:#ffadae}#empty{text-align:center;color:#9eacc0;padding:28px}footer{margin:24px 0;color:#8d9db6;line-height:1.7;font-size:13px}[hidden]{display:none!important}@media(max-width:600px){main{margin:24px auto;padding:0 14px}section{padding:16px}h1{font-size:25px}header{align-items:flex-start}.badge{font-size:12px;padding:6px 10px}th:nth-child(2){width:65px}th:last-child{width:115px}td button{padding:6px;font-size:12px}}
</style><main><header><div><small>POCKET HOME / SD CARD</small><h1>无线文件传输</h1><div class="muted">文件留在 SD 卡，屏幕照常使用。</div></div><span class="badge">本地 Wi-Fi</span></header>
<section id="login"><h2>连接你的屏幕</h2><p class="muted">在屏幕控制中心开启“文件传输”，输入显示的 6 位访问码。</p><form id="auth" class="row"><input id="code" type="password" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="6 位访问码" aria-label="访问码" required autocomplete="off"><button class="primary">连接</button></form></section>
<section id="panel" hidden><div class="row"><h2 id="crumb">SD 卡 /</h2><button id="up">上一级</button><button id="refresh">刷新</button><button id="lock">断开网页</button></div>
<div id="drop"><strong>把文件拖到这里</strong><p>或选择文件，上传至当前目录</p><button id="choose" class="primary">选择文件</button><input id="input" type="file" multiple hidden><p><small>单个文件最多 128 MB · 同名文件不会覆盖</small></p></div>
<div class="row"><span id="activity" class="muted">就绪</span><button id="cancel" hidden>取消传输</button></div><progress id="progress" max="100" value="0" hidden></progress>
<table><thead><tr><th>文件名</th><th>大小</th><th>操作</th></tr></thead><tbody id="files"></tbody></table><div id="empty" hidden>此目录还没有文件</div></section>
<p id="message" role="status"></p><footer>电脑与屏幕需连接同一网络。传输速度优先保证屏幕响应。<br>使用完毕后，在屏幕控制中心关闭文件传输；每次开启会生成新访问码。</footer></main>
<script>
'use strict';const $=id=>document.getElementById(id);let key='',directory='',active=false,xhr=null,aborter=null;
const say=(s,bad=false)=>{$('message').textContent=s;$('message').style.color=bad?'#ffadae':'#71e6b1'};
function busy(v){active=v;for(const id of ['choose','up','refresh','lock'])$(id).disabled=v;$('progress').hidden=!v;$('cancel').hidden=!v;if(!v)$('activity').textContent='就绪'}
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'X-File-Key':key,...options.headers},cache:'no-store'});if(!r.ok)throw Error(await r.text()||'请求失败');return r}
const path=n=>directory?directory+'/'+n:n;const size=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
async function refresh(){const r=await api('/api/list?dir='+encodeURIComponent(directory));const d=await r.json();$('files').replaceChildren();$('crumb').textContent='SD 卡 /'+directory;$('up').hidden=!directory;$('empty').hidden=d.files.length>0;
for(const f of d.files){const tr=document.createElement('tr'),name=document.createElement('td'),amount=document.createElement('td'),actions=document.createElement('td');name.textContent=(f.dir?'📁 ':'')+f.name;amount.textContent=f.dir?'目录':size(f.size);const b=document.createElement('button');b.textContent=f.dir?'打开':'下载';b.onclick=async()=>{if(active)return;if(f.dir){const old=directory;directory=path(f.name);try{await refresh()}catch(e){directory=old;say(e.message,true)}}else await download(f.name)};actions.append(b);if(!f.dir){const del=document.createElement('button');del.textContent='删除';del.className='danger';del.onclick=async()=>{if(active||!confirm('确定删除“'+f.name+'”？此操作无法撤销。'))return;try{await api('/api/file?name='+encodeURIComponent(path(f.name)),{method:'DELETE'});say('已删除 '+f.name);await refresh()}catch(e){say(e.message,true)}};actions.append(del)}tr.append(name,amount,actions);$('files').append(tr)}if(d.truncated)say('目录较大，仅显示前 256 项。',true)}
$('auth').onsubmit=async e=>{e.preventDefault();key=$('code').value;directory='';try{await refresh();$('login').hidden=true;$('panel').hidden=false;$('code').value='';say('已连接，可以传文件了。')}catch(e){key='';say(e.message,true)}};
$('refresh').onclick=()=>refresh().catch(e=>say(e.message,true));$('up').onclick=()=>{directory=directory.split('/').slice(0,-1).join('/');refresh().catch(e=>say(e.message,true))};$('lock').onclick=()=>{key='';$('panel').hidden=true;$('login').hidden=false;say('网页已断开。关闭服务请使用屏幕开关。')};$('choose').onclick=()=>{if(!active)$('input').click()};$('input').onchange=e=>upload(e.target.files);
function send(file){return new Promise((resolve,reject)=>{xhr=new XMLHttpRequest();xhr.open('POST','/api/file?name='+encodeURIComponent(path(file.name)));xhr.setRequestHeader('X-File-Key',key);xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.upload.onprogress=e=>{if(e.lengthComputable)$('progress').value=e.loaded*100/e.total};xhr.onload=()=>xhr.status===200?resolve():reject(Error(xhr.responseText||'上传失败'));xhr.onerror=()=>reject(Error('连接中断，请确认屏幕的文件传输仍开启'));xhr.onabort=()=>reject(Error('上传已取消'));xhr.send(file)})}
async function upload(files){if(active||!files.length)return;busy(true);try{for(const f of files){if(f.size>128*1024*1024)throw Error(f.name+' 超过 128 MB');$('progress').value=0;$('activity').textContent='上传 '+f.name;await send(f);say('已上传 '+f.name)}await refresh()}catch(e){say(e.message,true)}finally{xhr=null;$('input').value='';busy(false)}}
async function download(n){busy(true);$('activity').textContent='下载 '+n;$('progress').removeAttribute('value');aborter=new AbortController();try{const r=await api('/api/file?name='+encodeURIComponent(path(n)),{signal:aborter.signal});const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);say('已下载 '+n)}catch(e){say(e.name==='AbortError'?'下载已取消':e.message,true)}finally{aborter=null;busy(false)}}
$('cancel').onclick=()=>{if(xhr)xhr.abort();if(aborter)aborter.abort()};for(const e of ['dragenter','dragover'])$('drop').addEventListener(e,x=>{x.preventDefault();if(!active)$('drop').classList.add('over')});for(const e of ['dragleave','drop'])$('drop').addEventListener(e,x=>{x.preventDefault();$('drop').classList.remove('over')});$('drop').addEventListener('drop',e=>upload(e.dataTransfer.files));window.addEventListener('beforeunload',e=>{if(active){e.preventDefault();e.returnValue=''}});
</script></html>)HTML";
