idf_component_register(
    SRCS
        "clock_ui.cpp"
        "energy_view.cpp"
        "devices_view.cpp"
        "fonts/energy_digits_64.c"
        "fonts/clock_cjk_16.c"
        "fonts/clock_cjk_24.c"
        "fonts/clock_cjk_32.c"
        "fonts/clock_cjk_96.c"
    INCLUDE_DIRS "include"
    REQUIRES
        board
        ha_devices
        energy_service
        settings
        time_service
        wifi_manager
        lunar
    PRIV_REQUIRES
        lvgl__lvgl
        espressif__esp_lvgl_adapter
)
