#!/usr/bin/env python3
"""Build split-flap RGB565 tiles in Flash, avoiding transformed LVGL layers.
Requires Pillow and the SIL OFL Source Han Sans Bold font (see fonts license).
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import argparse
p=argparse.ArgumentParser();p.add_argument('--font',default='/tmp/SourceHanSansSC-Bold.otf');a=p.parse_args()
root=Path(__file__).resolve().parents[1]
font=ImageFont.truetype(a.font,112)
out=['// Generated by tools/generate_flip_tiles.py; Source Han Sans, SIL OFL.\n#include "lvgl.h"\n']
for digit,char in enumerate('0123456789-'):
    image=Image.new('RGB',(76,184),(0x22,0x26,0x30))
    draw=ImageDraw.Draw(image);draw.rectangle((0,94,75,183),fill=(0x28,0x2c,0x35))
    bbox=font.getbbox(char);w=bbox[2]-bbox[0];h=bbox[3]-bbox[1]
    draw.text(((76-w)/2-bbox[0],(184-h)/2-bbox[1]),char,font=font,fill=(244,247,255))
    for half,y in enumerate((0,94)):
        pixels=list(image.crop((0,y,76,y+90)).getdata())
        values=[((r>>3)<<11)|((g>>2)<<5)|(b>>3) for r,g,b in pixels]
        out.append('static const uint16_t tile_%d_%d[] = {\n'%(digit,half))
        out.extend(','.join('0x%04x'%n for n in values[i:i+24])+',\n' for i in range(0,len(values),24));out.append('};\n')
out.append('const lv_image_dsc_t pocket_flip_tiles[11][2] = {\n')
for d in range(11):
    out.append('{\n')
    for h in range(2):
        out.append('{.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.flags=0,.w=76,.h=90,.stride=152},.data_size=sizeof(tile_%d_%d),.data=(const uint8_t*)tile_%d_%d},\n'%(d,h,d,h))
    out.append('},\n')
out.append('};\n');(root/'main/fonts/flip_tiles.c').write_text(''.join(out))
